modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
modId = "klib"
version = "${version}"
displayName = "KLib"
description = "Lat's random utility and math stuff library"
authors = "latvian.dev"
logoFile = "klib_logo.png"
logoBlur = false

[[dependencies.klib]]
modId = "neoforge"
type = "required"
versionRange = "[21.5.75,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "klib.mixins.json"