name: Java CI (Main)

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[ci skip]')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 30

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build -x test --stacktrace

      - name: Publish to latvian.dev Maven
        uses: gradle/gradle-build-action@v2
        env:
          MAVEN_URL: 'https://maven.latvian.dev/releases'
          MAVEN_USERNAME: 'lat'
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
        with:
          arguments: publish --stacktrace
